### ISSUE TITLE
Find suitable ngo template

### ISSUE THREAD

**Issue by paragasu** [phisoft/edulifeborneo-web#1]
[Website content EduLife.pdf](https://github.com/phisoft/edulifeborneo-web/files/8648413/Website.content.EduLife.pdf)

**Comment by russel0907** [comment]
Find suitable ngo template ;

# Template 1
![image](https://user-images.githubusercontent.com/94702093/167337150-f67e5b09-f29c-4710-a21e-5aeff62f0e79.png)
https://technext.github.io/welfare/index.html
<br>
# Template 2
![image](https://user-images.githubusercontent.com/94702093/167337198-8db9721d-00ec-460c-8595-3460683e7c37.png)
https://technext.github.io/fundraiser/index.html
<br>
# Template 3
![image](https://user-images.githubusercontent.com/94702093/167337227-5d846067-9a31-4617-a38a-4599309442d6.png)
https://technext.github.io/charifit/index.html
<br>
# Template 4
![image](https://user-images.githubusercontent.com/94702093/167337249-9d8eb282-8cf8-4e8e-819b-ec52c3389f3f.png)
https://technext.github.io/foundation/index.html#
<br>
# Template 5
![image](https://user-images.githubusercontent.com/94702093/167337278-041d47a0-e49a-4ae3-a551-add0d3454928.png)
https://html.design/demo/givelife/index.html

**Comment by rosclaritha** [comment]
@russel0907 
Proceed issue https://github.com/phisoft/edulifeborneo-web/issues/2 with Template 4 https://technext.github.io/foundation/index.html#
