### ISSUE TITLE
Optimize image

### ISSUE THREAD

**Issue by paragasu** [phisoft/edulifeborneo-web#4]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/167543604-207bb069-108a-4ace-881c-4d140dbd0363.png">

**Comment by russel0907** [comment]
Optimize image. Reduce image size < 500kb ;

![Screenshot (313)](https://user-images.githubusercontent.com/94702093/167565245-213bb741-2429-46ca-a2d7-b98d75fc49ae.png)
